-- USER SQL
ALTER USER "HR" IDENTIFIED BY "hi123456" 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "HR" QUOTA UNLIMITED ON "USERS";

-- ROLES
ALTER USER "HR" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES

-- -------------------------------------------------------
-- USER SQL
CREATE USER "TEST" IDENTIFIED BY "hi123456"  ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "TEST" ;
GRANT "RESOURCE" TO "TEST" ;

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "TEST" ;

